"""
Lowering — Internal IR → MLIR mapping
======================================
两条路径:

  lower_to_mlir_text(graph)   → str          （调试 / IR dump）
  lower_to_mlir_module(graph) → ir.Module    （工业级，直接对接 MLIRCompiler）

工业级路径核心思路
------------------
文本生成（text-gen）的问题:
  IRGraph → 字符串 → (消费方需要重新解析成 MLIR IR)

工业级路径:
  IRGraph → ir.Module (f32 + RankedTensorType + FloatAttr/BoolAttr/IntegerAttr + 真实 SSA Value)
          → MLIRCompiler._find_fused_op()  ← 直接读 ir.Operation.attributes，免去 export_and_import()
          → 提取 scale / is_causal / softmax_dim → Triton codegen

两者的本质区别
--------------
text-gen:
  - SSA: 字符串 "%node_name"（无类型检查，无 def-use 约束）
  - 属性: f-string 数字文本（无 MLIR schema 验证）
  - 输出: str，消费方必须重新 parse/import

ir.Module-gen:
  - SSA: ir.Value 对象（ir.BlockArgument / ir.OpResult），def-use 由 MLIR C++ 层管理
  - 属性: ir.FloatAttr / ir.BoolAttr / ir.IntegerAttr（通过 MLIR C API 构造，schema 合法）
  - 类型: ir.RankedTensorType.get(dims, f32)（真实 shaped type）
  - 输出: ir.Module，可直接传入 run_attention_fusion_pass() 或 MLIRCompiler._find_fused_op()

若 torch_mlir 不可用，lower_to_mlir_module() 抛出 ImportError；lower_to_mlir_text() 始终可用。
"""

from __future__ import annotations

from typing import List, Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from compiler.ir.graph import IRGraph, IRNode

from compiler.ir.ops import OpType


# MLIR shape 格式: None / -1 -> "?"
def _shape_str(node: "IRNode") -> str:
    if node.output_shape is None:
        return "tensor<?x?x?x?xf32>"
    dims = ["?" if d == -1 else str(d) for d in node.output_shape.dims]
    return f"tensor<{'x'.join(dims)}xf32>"


def lower_to_mlir_text(graph: "IRGraph") -> str:
    """
    将 IRGraph 转换为 MLIR 文本（custom dialect）。

    Returns:
        MLIR 函数文本字符串（用于调试 / dump）
    """
    try:
        ordered = graph.topological_sort()
    except ValueError:
        ordered = graph.nodes

    lines: List[str] = []
    lines.append(f"// IRGraph: {graph.name}")
    lines.append("// Generated by compiler/lowering/to_mlir.py")
    lines.append("")

    # 收集函数参数（INPUT 节点）
    input_nodes = [n for n in ordered if n.op_type == OpType.INPUT]
    params = ", ".join(
        f"%{n.name}: {_shape_str(n)}" for n in input_nodes
    )

    # 收集输出类型（OUTPUT 节点的输入 shape）
    output_nodes = [n for n in ordered if n.op_type == OpType.OUTPUT]
    if output_nodes and output_nodes[0].inputs:
        out_node_name = output_nodes[0].inputs[0]
        try:
            out_node = graph.get_node(out_node_name)
            ret_type = _shape_str(out_node)
        except KeyError:
            ret_type = "tensor<?x?x?x?xf32>"
    else:
        ret_type = "tensor<?x?x?x?xf32>"

    lines.append(f"func.func @{graph.name}({params}) -> {ret_type} {{")

    for node in ordered:
        line = _emit_node(node)
        if line:
            lines.append(f"  {line}")

    # 返回语句
    if output_nodes and output_nodes[0].inputs:
        ret_val = output_nodes[0].inputs[0]
        lines.append(f"  return %{ret_val} : {ret_type}")
    lines.append("}")

    return "\n".join(lines)


def _emit_node(node: "IRNode") -> str:
    """将单个 IRNode 转换为 MLIR op 文本行。"""
    shape = _shape_str(node)

    if node.op_type == OpType.INPUT:
        return f"// input: %{node.name} -> {shape}"

    if node.op_type == OpType.OUTPUT:
        return ""  # 由 return 语句处理

    if node.op_type == OpType.MATMUL:
        a, b = node.inputs[0], node.inputs[1]
        return (
            f"%{node.name} = torch.aten.matmul %{a}, %{b} "
            f": {shape}, {shape} -> {shape}"
        )

    if node.op_type == OpType.SCALE:
        inp = node.inputs[0] if node.inputs else "undef"
        scale = node.attrs.get("scale_factor", 1.0)
        return (
            f"%{node.name} = torch.aten.mul.Scalar %{inp}, "
            f"{scale:.6f} : {shape}, f64 -> {shape}"
        )

    if node.op_type == OpType.MASK:
        inp = node.inputs[0] if node.inputs else "undef"
        return (
            f"%{node.name} = torch.aten.masked_fill.Scalar %{inp}, "
            f"%causal_mask, 0xFF800000 : {shape}, !torch.bool, f32 -> {shape}"
        )

    if node.op_type == OpType.SOFTMAX:
        inp = node.inputs[0] if node.inputs else "undef"
        dim = node.attrs.get("dim", -1)
        return (
            f"%{node.name} = torch.aten._softmax %{inp}, "
            f"{dim} : i64, %false : i1 -> {shape}"
        )

    if node.op_type == OpType.FUSED_SCALE_MASK_SOFTMAX:
        inp = node.inputs[0] if node.inputs else "undef"
        scale = node.attrs.get("scale_factor", 1.0)
        is_causal = str(node.attrs.get("is_causal", True)).lower()
        dim = node.attrs.get("softmax_dim", -1)
        fused_from = node.meta.get("fused_from", [])
        comment = f"  // fused from: {fused_from}" if fused_from else ""
        return (
            f'%{node.name} = "custom.fused_scaled_masked_softmax"(%{inp}) '
            f'{{scale = {scale:.6f} : f32, is_causal = {is_causal}, '
            f'softmax_dim = {dim} : i64}} : ({shape}) -> {shape}'
            f"{comment}"
        )

    if node.op_type == OpType.ATTENTION_SCORE:
        q, k, v = (node.inputs + ["undef"] * 3)[:3]
        return (
            f"%{node.name} = torch.aten.scaled_dot_product_attention "
            f"%{q}, %{k}, %{v} : {shape} -> {shape}"
        )

    # 未知 op 用注释占位
    return f"// unknown op: %{node.name} = {node.op_type.name}({', '.join(node.inputs)})"


# =====================================================================
# 工业级路径: IRGraph → ir.Module (真实 MLIR Python 对象)
# =====================================================================

def lower_to_mlir_module(graph: "IRGraph"):
    """
    工业级 IR → MLIR codegen。

    返回 torch_mlir.ir.Module，可直接插入现有编译链:
        lower_to_mlir_module(graph) → ir.Module
          → MLIRCompiler._find_fused_op(module)    # 直接读 ir.Operation.attributes
          → 提取 scale / is_causal / softmax_dim
          → Triton codegen

    与 lower_to_mlir_text() 的本质区别
    ------------------------------------
    text-gen:
      "%fused = custom.fused_scaled_masked_softmax ..."   # 字符串，无类型系统
      消费方必须重新 parse / verify

    ir.Module-gen（本函数）:
      ir.Operation.create(
          "custom.fused_scaled_masked_softmax",
          results=[ir.RankedTensorType.get(dims, f32)],      # 真实 shaped type
          operands=[ir.Value],                                # 真实 SSA value
          attributes={
              "scale":       ir.FloatAttr.get(f32, 0.125),   # MLIR C API 属性对象
              "is_causal":   ir.BoolAttr.get(True),
              "softmax_dim": ir.IntegerAttr.get(i64, -1),
          },
      )
      ir.BlockArgument / ir.OpResult 构成完整 def-use 链，
      可直接传入 run_attention_fusion_pass() 或 _find_fused_op()。

    Relations to existing passes
    ------------------------------
    - 若图中已有 FUSED_SCALE_MASK_SOFTMAX 节点（经过 fusion pass），
      本函数直接生成 custom.fused_scaled_masked_softmax op，
      MLIRCompiler._find_fused_op() 可就立刻读到属性，
      无需再跑 run_attention_fusion_pass()。

    - 若图中还是 SCALE→MASK→SOFTMAX 未融合节点，
      本函数生成 torch aten ops，
      随后可对生成的 ir.Module 运行 run_attention_fusion_pass()。

    Raises:
        ImportError: 若 torch_mlir 未安装。
    """
    try:
        from torch_mlir import ir
        from torch_mlir.dialects import func as func_d
    except ImportError as exc:
        raise ImportError(
            "torch_mlir is required for lower_to_mlir_module(). "
            "Use lower_to_mlir_text() for a text-only fallback."
        ) from exc

    with ir.Context() as ctx, ir.Location.unknown():
        # 注册 torch 方言（torch_mlir 使用 torch dialect 类型前缀）
        try:
            from torch_mlir.dialects import torch as torch_d  # noqa: F401
        except ImportError:
            pass  # 部分构建不带 torch dialect Python 绑定，继续用 generic op

        module = ir.Module.create()

        # --- 基础 MLIR 类型 ---
        f32 = ir.F32Type.get()
        i64 = ir.IntegerType.get_signless(64)

        try:
            ordered: List["IRNode"] = graph.topological_sort()
        except ValueError:
            ordered = list(graph.nodes)

        input_nodes  = [n for n in ordered if n.op_type == OpType.INPUT]
        output_nodes = [n for n in ordered if n.op_type == OpType.OUTPUT]

        def _mlir_tensor_type(node: "IRNode") -> ir.Type:
            """IRNode.output_shape → ir.RankedTensorType（或 unranked fallback）。"""
            if node.output_shape is None:
                return ir.UnrankedTensorType.get(f32)
            dims = [d if d != -1 else -1 for d in node.output_shape.dims]
            return ir.RankedTensorType.get(dims, f32)

        # --- 函数签名 ---
        input_types = [_mlir_tensor_type(n) for n in input_nodes]

        if output_nodes and output_nodes[0].inputs:
            try:
                out_src = graph.get_node(output_nodes[0].inputs[0])
                result_types = [_mlir_tensor_type(out_src)]
            except KeyError:
                result_types = [ir.UnrankedTensorType.get(f32)]
        else:
            result_types = [ir.UnrankedTensorType.get(f32)]

        func_type = ir.FunctionType.get(input_types, result_types)

        with ir.InsertionPoint(module.body):
            func_op = func_d.FuncOp(graph.name, func_type)
            entry = func_op.add_entry_block()

            with ir.InsertionPoint(entry):
                # value_map: node name → ir.Value（SSA value，非字符串）
                value_map: Dict[str, "ir.Value"] = {
                    n.name: entry.arguments[i]
                    for i, n in enumerate(input_nodes)
                }

                for node in ordered:
                    if node.op_type in (OpType.INPUT, OpType.OUTPUT):
                        continue

                    result_type = _mlir_tensor_type(node)

                    # ── FUSED_SCALE_MASK_SOFTMAX ──────────────────────────────────
                    # 对应 MLIR custom.fused_scaled_masked_softmax op，
                    # 属性用 ir.*Attr 对象（非字符串），可被 _find_fused_op() 直接读取。
                    if node.op_type == OpType.FUSED_SCALE_MASK_SOFTMAX:
                        inp_val = (
                            value_map[node.inputs[0]]
                            if node.inputs and node.inputs[0] in value_map
                            else entry.arguments[0]
                        )
                        op = ir.Operation.create(
                            "custom.fused_scaled_masked_softmax",
                            results=[result_type],
                            operands=[inp_val],
                            attributes={
                                # ir.FloatAttr: C API FloatAttr，被 MLIRCompiler 直接读
                                "scale": ir.FloatAttr.get(
                                    f32, float(node.attrs.get("scale_factor", 1.0))
                                ),
                                # ir.BoolAttr: 被 ir.BoolAttr(attrs["is_causal"]).value 读
                                "is_causal": ir.BoolAttr.get(
                                    bool(node.attrs.get("is_causal", True))
                                ),
                                # ir.IntegerAttr: 被 ir.IntegerAttr(attrs["softmax_dim"]) 读
                                "softmax_dim": ir.IntegerAttr.get(
                                    i64, int(node.attrs.get("softmax_dim", -1))
                                ),
                            },
                        )
                        value_map[node.name] = op.result

                    # ── MATMUL ────────────────────────────────────────────────────
                    elif node.op_type == OpType.MATMUL:
                        a = value_map.get(node.inputs[0], entry.arguments[0]) if node.inputs else entry.arguments[0]
                        b = value_map.get(node.inputs[1], entry.arguments[0]) if len(node.inputs) > 1 else entry.arguments[0]
                        op = ir.Operation.create(
                            "torch.aten.matmul",
                            results=[result_type],
                            operands=[a, b],
                        )
                        value_map[node.name] = op.result

                    # ── SCALE (mul.Scalar) ────────────────────────────────────────
                    elif node.op_type == OpType.SCALE:
                        inp_val = (
                            value_map[node.inputs[0]]
                            if node.inputs and node.inputs[0] in value_map
                            else entry.arguments[0]
                        )
                        op = ir.Operation.create(
                            "torch.aten.mul.Scalar",
                            results=[result_type],
                            operands=[inp_val],
                            attributes={
                                "value": ir.FloatAttr.get(
                                    f32, float(node.attrs.get("scale_factor", 1.0))
                                )
                            },
                        )
                        value_map[node.name] = op.result

                    # ── MASK (masked_fill) ─────────────────────────────────────────
                    elif node.op_type == OpType.MASK:
                        inp_val = (
                            value_map[node.inputs[0]]
                            if node.inputs and node.inputs[0] in value_map
                            else entry.arguments[0]
                        )
                        neg_inf = ir.FloatAttr.get(f32, float("-inf"))
                        op = ir.Operation.create(
                            "torch.aten.masked_fill.Scalar",
                            results=[result_type],
                            operands=[inp_val],
                            attributes={"fill_value": neg_inf},
                        )
                        value_map[node.name] = op.result

                    # ── SOFTMAX ────────────────────────────────────────────────────
                    elif node.op_type == OpType.SOFTMAX:
                        inp_val = (
                            value_map[node.inputs[0]]
                            if node.inputs and node.inputs[0] in value_map
                            else entry.arguments[0]
                        )
                        dim = int(node.attrs.get("dim", -1))
                        op = ir.Operation.create(
                            "torch.aten._softmax",
                            results=[result_type],
                            operands=[inp_val],
                            attributes={"dim": ir.IntegerAttr.get(i64, dim)},
                        )
                        value_map[node.name] = op.result

                    # ── ATTENTION_SCORE ────────────────────────────────────────────
                    elif node.op_type == OpType.ATTENTION_SCORE:
                        q = value_map.get(node.inputs[0], entry.arguments[0]) if node.inputs else entry.arguments[0]
                        k = value_map.get(node.inputs[1], entry.arguments[0]) if len(node.inputs) > 1 else entry.arguments[0]
                        v = value_map.get(node.inputs[2], entry.arguments[0]) if len(node.inputs) > 2 else entry.arguments[0]
                        op = ir.Operation.create(
                            "torch.aten.scaled_dot_product_attention",
                            results=[result_type],
                            operands=[q, k, v],
                        )
                        value_map[node.name] = op.result

                    else:
                        # 未知 op：占位 undef；保证 value_map 不断链
                        op = ir.Operation.create(
                            "compiler.undef",
                            results=[result_type],
                            operands=[],
                        )
                        value_map[node.name] = op.result

                # --- 返回语句 ---
                if output_nodes and output_nodes[0].inputs:
                    ret_name = output_nodes[0].inputs[0]
                    ret_val = value_map.get(ret_name, entry.arguments[0])
                else:
                    ret_val = entry.arguments[0]
                func_d.ReturnOp([ret_val])

        return module
